// MARK: - HTML Attribute Properties
extension HtmlAttr {
    // Global Attributes
    public static let accesskey = HtmlAttr(key: "accesskey")
    public static let autocapitalize = HtmlAttr(key: "autocapitalize")
    public static let `class` = HtmlAttr(key: "class")
    public static let contenteditable = HtmlAttr(key: "contenteditable")
    public static let dir = HtmlAttr(key: "dir")
    public static let draggable = HtmlAttr(key: "draggable")
    public static let enterkeyhint = HtmlAttr(key: "enterkeyhint")
    public static let hidden = HtmlAttr(key: "hidden")
    public static let id = HtmlAttr(key: "id")
    public static let inputmode = HtmlAttr(key: "inputmode")
    public static let `is` = HtmlAttr(key: "is")
    public static let itemid = HtmlAttr(key: "itemid")
    public static let itemprop = HtmlAttr(key: "itemprop")
    public static let itemref = HtmlAttr(key: "itemref")
    public static let itemscope = HtmlAttr(key: "itemscope")
    public static let itemtype = HtmlAttr(key: "itemtype")
    public static let lang = HtmlAttr(key: "lang")
    public static let nonce = HtmlAttr(key: "nonce")
    public static let spellcheck = HtmlAttr(key: "spellcheck")
    public static let style = HtmlAttr(key: "style")
    public static let tabindex = HtmlAttr(key: "tabindex")
    public static let title = HtmlAttr(key: "title")
    public static let translate = HtmlAttr(key: "translate")

    // Specific Element Attributes
    public static let accept = HtmlAttr(key: "accept") // <input>, <form>
    public static let accept_charset = HtmlAttr(key: "accept-charset") // <form>
    public static let action = HtmlAttr(key: "action") // <form>
    public static let align = HtmlAttr(key: "align") // Obsolete, but part of the spec
    public static let allow = HtmlAttr(key: "allow") // <iframe>
    public static let alt = HtmlAttr(key: "alt") // <img>, <area>, <input>
    public static let `async` = HtmlAttr(key: "async") // <script>
    public static let autocomplete = HtmlAttr(key: "autocomplete") // <form>, <input>, etc.
    public static let autofocus = HtmlAttr(key: "autofocus") // <button>, <input>, etc.
    public static let autoplay = HtmlAttr(key: "autoplay") // <audio>, <video>
    public static let charset = HtmlAttr(key: "charset") // <meta>, <script>
    public static let checked = HtmlAttr(key: "checked") // <input>
    public static let cite = HtmlAttr(key: "cite") // <blockquote>, <q>, <del>, etc.
    public static let cols = HtmlAttr(key: "cols") // <textarea>
    public static let colspan = HtmlAttr(key: "colspan") // <td>, <th>
    public static let content = HtmlAttr(key: "content") // <meta>
    public static let controls = HtmlAttr(key: "controls") // <audio>, <video>
    public static let coords = HtmlAttr(key: "coords") // <area>
    public static let crossorigin = HtmlAttr(key: "crossorigin") // <img>, <audio>, <video>, etc.
    public static let datetime = HtmlAttr(key: "datetime") // <time>, <ins>, <del>
    public static let decoding = HtmlAttr(key: "decoding") // <img>
    public static let defaultAttr = HtmlAttr(key: "default") // <track>
    public static let `defer` = HtmlAttr(key: "defer") // <script>
    public static let disabled = HtmlAttr(key: "disabled") // <button>, <input>, etc.
    public static let download = HtmlAttr(key: "download") // <a>, <area>
    public static let enctype = HtmlAttr(key: "enctype") // <form>
    public static let `for` = HtmlAttr(key: "for") // <label>, <output>
    public static let form = HtmlAttr(key: "form") // <button>, <input>, etc.
    public static let formaction = HtmlAttr(key: "formaction") // <button>, <input>
    public static let formenctype = HtmlAttr(key: "formenctype") // <button>, <input>
    public static let formmethod = HtmlAttr(key: "formmethod") // <button>, <input>
    public static let formnovalidate = HtmlAttr(key: "formnovalidate") // <button>, <input>
    public static let formtarget = HtmlAttr(key: "formtarget") // <button>, <input>
    public static let headers = HtmlAttr(key: "headers") // <td>, <th>
    public static let height = HtmlAttr(key: "height") // <img>, <video>, etc.
    public static let high = HtmlAttr(key: "high") // <meter>
    public static let href = HtmlAttr(key: "href") // <a>, <link>, etc.
    public static let hreflang = HtmlAttr(key: "hreflang") // <a>, <link>
    public static let inert = HtmlAttr(key: "inert") // <link>, <script>
    public static let integrity = HtmlAttr(key: "integrity") // <link>, <script>
    public static let kind = HtmlAttr(key: "kind") // <track>
    public static let label = HtmlAttr(key: "label") // <track>, <option>, etc.
    public static let list = HtmlAttr(key: "list") // <input>
    public static let loop = HtmlAttr(key: "loop") // <audio>, <video>
    public static let low = HtmlAttr(key: "low") // <meter>e
    public static let max = HtmlAttr(key: "max") // <input>, <meter>, <progress>
    public static let maxlength = HtmlAttr(key: "maxlength") // <input>, <textarea>
    public static let min = HtmlAttr(key: "min") // <input>, <meter>
    public static let minlength = HtmlAttr(key: "minlength") // <input>, <textarea>
    public static let multiple = HtmlAttr(key: "multiple") // <input>, <select>
    public static let muted = HtmlAttr(key: "muted") // <audio>, <video>
    public static let name = HtmlAttr(key: "name") // <input>, <form>, etc.
    public static let novalidate = HtmlAttr(key: "novalidate") // <form>
    public static let `open` = HtmlAttr(key: "open") // <details>, <dialog>
    public static let optimum = HtmlAttr(key: "optimum") // <meter>
    public static let part = HtmlAttr(key: "part") // <input>
    public static let pattern = HtmlAttr(key: "pattern") // <input>
    public static let ping = HtmlAttr(key: "ping") // <input>
    public static let placeholder = HtmlAttr(key: "placeholder") // <input>, <textarea>
    public static let poster = HtmlAttr(key: "poster") // <video>
    public static let preload = HtmlAttr(key: "preload") // <audio>, <video>
    public static let readonly = HtmlAttr(key: "readonly") // <input>, <textarea>
    public static let referrerpolicy = HtmlAttr(key: "referrerpolicy") // <input>, <textarea>
    public static let rel = HtmlAttr(key: "rel") // <a>, <link>
    public static let `required` = HtmlAttr(key: "required") // <input>, <select>, etc.
    public static let reversed = HtmlAttr(key: "reversed") // <ol>
    public static let rows = HtmlAttr(key: "rows") // <textarea>
    public static let rowspan = HtmlAttr(key: "rowspan") // <td>, <th>
    public static let sandbox = HtmlAttr(key: "sandbox") // <iframe>
    public static let scope = HtmlAttr(key: "scope") // <th>
    public static let selected = HtmlAttr(key: "selected") // <option>
    public static let shape = HtmlAttr(key: "shape") // <area>
    public static let size = HtmlAttr(key: "size") // <input>, <select>
    public static let sizes = HtmlAttr(key: "sizes") // <link>, <img>
    public static let slot = HtmlAttr(key: "slot") // Web components
    public static let span = HtmlAttr(key: "span") 
    public static let src = HtmlAttr(key: "src") // <img>, <script>, etc.
    public static let srcdoc = HtmlAttr(key: "srcdoc") // <iframe>
    public static let srclang = HtmlAttr(key: "srclang") // <track>
    public static let srcset = HtmlAttr(key: "srcset") // <img>, <source>
    public static let start = HtmlAttr(key: "start") // <ol>
    public static let step = HtmlAttr(key: "step") // <input>
    public static let target = HtmlAttr(key: "target") // <a>, <form>
    public static let type = HtmlAttr(key: "type") // <button>, <input>, etc.
    public static let value = HtmlAttr(key: "value") // <button>, <input>, etc.
    public static let width = HtmlAttr(key: "width") // <img>, <video>, etc.
    public static let wrap = HtmlAttr(key: "wrap") // <textarea>
}

