// MARK: - HTML Event Attribute Properties
extension Attr { // Changed from HtmlAttr
    public struct on {
        public static func event(_ event: String) -> AttributeKey<String> { // Changed return type
            return AttributeKey<String>(key: "on\(event)") // Changed implementation
        }

        // Standard HTML Event Attributes
        public static let abort = AttributeKey<String>(key: "onabort") // Changed to AttributeKey<String>
        public static let afterprint = AttributeKey<String>(key: "onafterprint")
        public static let beforeprint = AttributeKey<String>(key: "onbeforeprint")
        public static let beforeunload = AttributeKey<String>(key: "onbeforeunload")
        public static let blur = AttributeKey<String>(key: "onblur")
        public static let cancel = AttributeKey<String>(key: "oncancel")
        public static let canplay = AttributeKey<String>(key: "oncanplay")
        public static let canplaythrough = AttributeKey<String>(key: "oncanplaythrough")
        public static let change = AttributeKey<String>(key: "onchange")
        public static let click = AttributeKey<String>(key: "onclick") // Changed to AttributeKey<String>
        public static let close = AttributeKey<String>(key: "onclose")
        public static let contextmenu = AttributeKey<String>(key: "oncontextmenu")
        public static let copy = AttributeKey<String>(key: "oncopy")
        public static let cuechange = AttributeKey<String>(key: "oncuechange")
        public static let cut = AttributeKey<String>(key: "oncut")
        public static let dblclick = AttributeKey<String>(key: "ondblclick")
        public static let drag = AttributeKey<String>(key: "ondrag")
        public static let dragend = AttributeKey<String>(key: "ondragend")
        public static let dragenter = AttributeKey<String>(key: "ondragenter")
        public static let dragleave = AttributeKey<String>(key: "ondragleave")
        public static let dragover = AttributeKey<String>(key: "ondragover")
        public static let dragstart = AttributeKey<String>(key: "ondragstart")
        public static let drop = AttributeKey<String>(key: "ondrop")
        public static let durationchange = AttributeKey<String>(key: "ondurationchange")
        public static let emptied = AttributeKey<String>(key: "onemptied")
        public static let ended = AttributeKey<String>(key: "onended")
        public static let error = AttributeKey<String>(key: "onerror")
        public static let focus = AttributeKey<String>(key: "onfocus")
        public static let focusin = AttributeKey<String>(key: "onfocusin")
        public static let focusout = AttributeKey<String>(key: "onfocusout")
        public static let formdata = AttributeKey<String>(key: "onformdata")
        public static let hashchange = AttributeKey<String>(key: "onhashchange")
        public static let input = AttributeKey<String>(key: "oninput")
        public static let invalid = AttributeKey<String>(key: "oninvalid")
        public static let keydown = AttributeKey<String>(key: "onkeydown")
        public static let keypress = AttributeKey<String>(key: "onkeypress") // Deprecated, but included for compatibility
        public static let keyup = AttributeKey<String>(key: "onkeyup")
        public static let load = AttributeKey<String>(key: "onload")
        public static let loadeddata = AttributeKey<String>(key: "onloadeddata")
        public static let loadedmetadata = AttributeKey<String>(key: "onloadedmetadata")
        public static let loadstart = AttributeKey<String>(key: "onloadstart")
        public static let message = AttributeKey<String>(key: "onmessage") 
        public static let mousedown = AttributeKey<String>(key: "onmousedown")
        public static let mouseenter = AttributeKey<String>(key: "onmouseenter")
        public static let mouseleave = AttributeKey<String>(key: "onmouseleave")
        public static let mousemove = AttributeKey<String>(key: "onmousemove")
        public static let mouseout = AttributeKey<String>(key: "onmouseout")
        public static let mouseover = AttributeKey<String>(key: "onmouseover")
        public static let mouseup = AttributeKey<String>(key: "onmouseup")
        public static let mousewheel = AttributeKey<String>(key: "onmousewheel") // Deprecated
        public static let offline = AttributeKey<String>(key: "onoffline")
        public static let online = AttributeKey<String>(key: "ononline")
        public static let pagehide = AttributeKey<String>(key: "onpagehide")
        public static let pageshow = AttributeKey<String>(key: "onpageshow")
        public static let paste = AttributeKey<String>(key: "onpaste")
        public static let pause = AttributeKey<String>(key: "onpause")
        public static let play = AttributeKey<String>(key: "onplay")
        public static let playing = AttributeKey<String>(key: "onplaying")
        public static let popstate = AttributeKey<String>(key: "onpopstate")
        public static let progress = AttributeKey<String>(key: "onprogress")
        public static let ratechange = AttributeKey<String>(key: "onratechange")
        public static let resize = AttributeKey<String>(key: "onresize")
        public static let reset = AttributeKey<String>(key: "onreset")
        public static let scroll = AttributeKey<String>(key: "onscroll")
        public static let search = AttributeKey<String>(key: "onsearch")
        public static let seeked = AttributeKey<String>(key: "onseeked")
        public static let seeking = AttributeKey<String>(key: "onseeking")
        public static let select = AttributeKey<String>(key: "onselect")
        public static let stalled = AttributeKey<String>(key: "onstalled")
        public static let storage = AttributeKey<String>(key: "onstorage")
        public static let submit = AttributeKey<String>(key: "onsubmit")
        public static let suspend = AttributeKey<String>(key: "onsuspend")
        public static let timeupdate = AttributeKey<String>(key: "ontimeupdate")
        public static let toggle = AttributeKey<String>(key: "ontoggle")
        public static let unload = AttributeKey<String>(key: "onunload")
        public static let volumechange = AttributeKey<String>(key: "onvolumechange")
        public static let waiting = AttributeKey<String>(key: "onwaiting")
        public static let wheel = AttributeKey<String>(key: "onwheel") // Changed to AttributeKey<String>
    }
}
