// Sources/Markup/event.swift
import Markup // For AttributeKey

public struct EventAttributes {
    // Standard HTML Event Attributes
    public let abort = AttributeKey<String>(key: "onabort")
    public let afterprint = AttributeKey<String>(key: "onafterprint")
    public let beforeprint = AttributeKey<String>(key: "onbeforeprint")
    public let beforeunload = AttributeKey<String>(key: "onbeforeunload")
    public let blur = AttributeKey<String>(key: "onblur")
    public let cancel = AttributeKey<String>(key: "oncancel")
    public let canplay = AttributeKey<String>(key: "oncanplay")
    public let canplaythrough = AttributeKey<String>(key: "oncanplaythrough")
    public let change = AttributeKey<String>(key: "onchange")
    public let click = AttributeKey<String>(key: "onclick") // This is the canonical definition now
    public let close = AttributeKey<String>(key: "onclose")
    public let contextmenu = AttributeKey<String>(key: "oncontextmenu")
    public let copy = AttributeKey<String>(key: "oncopy")
    public let cuechange = AttributeKey<String>(key: "oncuechange")
    public let cut = AttributeKey<String>(key: "oncut")
    public let dblclick = AttributeKey<String>(key: "ondblclick")
    public let drag = AttributeKey<String>(key: "ondrag")
    public let dragend = AttributeKey<String>(key: "ondragend")
    public let dragenter = AttributeKey<String>(key: "ondragenter")
    public let dragleave = AttributeKey<String>(key: "ondragleave")
    public let dragover = AttributeKey<String>(key: "ondragover")
    public let dragstart = AttributeKey<String>(key: "ondragstart")
    public let drop = AttributeKey<String>(key: "ondrop")
    public let durationchange = AttributeKey<String>(key: "ondurationchange")
    public let emptied = AttributeKey<String>(key: "onemptied")
    public let ended = AttributeKey<String>(key: "onended")
    public let error = AttributeKey<String>(key: "onerror")
    public let focus = AttributeKey<String>(key: "onfocus")
    public let focusin = AttributeKey<String>(key: "onfocusin")
    public let focusout = AttributeKey<String>(key: "onfocusout")
    public let formdata = AttributeKey<String>(key: "onformdata")
    public let hashchange = AttributeKey<String>(key: "onhashchange")
    public let input = AttributeKey<String>(key: "oninput")
    public let invalid = AttributeKey<String>(key: "oninvalid")
    public let keydown = AttributeKey<String>(key: "onkeydown")
    public let keypress = AttributeKey<String>(key: "onkeypress") // Deprecated, but included for compatibility
    public let keyup = AttributeKey<String>(key: "onkeyup")
    public let load = AttributeKey<String>(key: "onload")
    public let loadeddata = AttributeKey<String>(key: "onloadeddata")
    public let loadedmetadata = AttributeKey<String>(key: "onloadedmetadata")
    public let loadstart = AttributeKey<String>(key: "onloadstart")
    public let message = AttributeKey<String>(key: "onmessage")
    public let mousedown = AttributeKey<String>(key: "onmousedown")
    public let mouseenter = AttributeKey<String>(key: "onmouseenter")
    public let mouseleave = AttributeKey<String>(key: "onmouseleave")
    public let mousemove = AttributeKey<String>(key: "onmousemove")
    public let mouseout = AttributeKey<String>(key: "onmouseout")
    public let mouseover = AttributeKey<String>(key: "onmouseover")
    public let mouseup = AttributeKey<String>(key: "onmouseup")
    public let mousewheel = AttributeKey<String>(key: "onmousewheel") // Deprecated
    public let offline = AttributeKey<String>(key: "onoffline")
    public let online = AttributeKey<String>(key: "ononline")
    public let pagehide = AttributeKey<String>(key: "onpagehide")
    public let pageshow = AttributeKey<String>(key: "onpageshow")
    public let paste = AttributeKey<String>(key: "onpaste")
    public let pause = AttributeKey<String>(key: "onpause")
    public let play = AttributeKey<String>(key: "onplay")
    public let playing = AttributeKey<String>(key: "onplaying")
    public let popstate = AttributeKey<String>(key: "onpopstate")
    public let progress = AttributeKey<String>(key: "onprogress")
    public let ratechange = AttributeKey<String>(key: "onratechange")
    public let resize = AttributeKey<String>(key: "onresize")
    public let reset = AttributeKey<String>(key: "onreset")
    public let scroll = AttributeKey<String>(key: "onscroll")
    public let search = AttributeKey<String>(key: "onsearch")
    public let seeked = AttributeKey<String>(key: "onseeked")
    public let seeking = AttributeKey<String>(key: "onseeking")
    public let select = AttributeKey<String>(key: "onselect")
    public let stalled = AttributeKey<String>(key: "onstalled")
    public let storage = AttributeKey<String>(key: "onstorage")
    public let submit = AttributeKey<String>(key: "onsubmit")
    public let suspend = AttributeKey<String>(key: "onsuspend")
    public let timeupdate = AttributeKey<String>(key: "ontimeupdate")
    public let toggle = AttributeKey<String>(key: "ontoggle")
    public let unload = AttributeKey<String>(key: "onunload")
    public let volumechange = AttributeKey<String>(key: "onvolumechange")
    public let waiting = AttributeKey<String>(key: "onwaiting")
    public let wheel = AttributeKey<String>(key: "onwheel")

    // The generic `event(_ event: String)` function is removed.
    // If custom events are needed, they can be defined explicitly or a different mechanism introduced later.
}

/// Accessor for HTML event attributes (e.g., `on.click`, `on.load`).
public let on = EventAttributes()
