import Testing
@testable import Songbird
@testable import Markup

@Test("[HTML Specification]: All Elements")
func testHtmlSpecElements() throws {
    // Non-self-closing elements
    #expect(a().render() == "<a></a>")
    #expect(abbr().render() == "<abbr></abbr>")
    #expect(address().render() == "<address></address>")
    #expect(article().render() == "<article></article>")
    #expect(aside().render() == "<aside></aside>")
    #expect(audio().render() == "<audio></audio>")
    #expect(b().render() == "<b></b>")
    #expect(body().render() == "<body></body>")
    #expect(button().render() == "<button></button>")
    #expect(canvas().render() == "<canvas></canvas>")
    #expect(caption().render() == "<caption></caption>")
    #expect(cite().render() == "<cite></cite>")
    #expect(code().render() == "<code></code>")
    #expect(colgroup().render() == "<colgroup></colgroup>")
    #expect(data().render() == "<data></data>")
    #expect(datalist().render() == "<datalist></datalist>")
    #expect(dd().render() == "<dd></dd>")
    #expect(del().render() == "<del></del>")
    #expect(details().render() == "<details></details>")
    #expect(dfn().render() == "<dfn></dfn>")
    #expect(dialog().render() == "<dialog></dialog>")
    #expect(div().render() == "<div></div>")
    #expect(dl().render() == "<dl></dl>")
    #expect(dt().render() == "<dt></dt>")
    #expect(em().render() == "<em></em>")
    #expect(fieldset().render() == "<fieldset></fieldset>")
    #expect(figcaption().render() == "<figcaption></figcaption>")
    #expect(figure().render() == "<figure></figure>")
    #expect(footer().render() == "<footer></footer>")
    #expect(form().render() == "<form></form>")
    #expect(h1().render() == "<h1></h1>")
    #expect(h2().render() == "<h2></h2>")
    #expect(h3().render() == "<h3></h3>")
    #expect(h4().render() == "<h4></h4>")
    #expect(h5().render() == "<h5></h5>")
    #expect(h6().render() == "<h6></h6>")
    #expect(head().render() == "<head></head>")
    #expect(header().render() == "<header></header>")
    #expect(html().render() == "<html></html>")
    #expect(i().render() == "<i></i>")
    #expect(ins().render() == "<ins></ins>")
    #expect(kbd().render() == "<kbd></kbd>")
    #expect(label().render() == "<label></label>")
    #expect(legend().render() == "<legend></legend>")
    #expect(li().render() == "<li></li>")
    #expect(main().render() == "<main></main>")
    #expect(map().render() == "<map></map>")
    #expect(mark().render() == "<mark></mark>")
    #expect(nav().render() == "<nav></nav>")
    #expect(noscript().render() == "<noscript></noscript>")
    #expect(object().render() == "<object></object>")
    #expect(ol().render() == "<ol></ol>")
    #expect(optgroup().render() == "<optgroup></optgroup>")
    #expect(option().render() == "<option></option>")
    #expect(output().render() == "<output></output>")
    #expect(p().render() == "<p></p>")
    #expect(picture().render() == "<picture></picture>")
    #expect(pre().render() == "<pre></pre>")
    #expect(progress().render() == "<progress></progress>")
    #expect(q().render() == "<q></q>")
    #expect(rp().render() == "<rp></rp>")
    #expect(rt().render() == "<rt></rt>")
    #expect(ruby().render() == "<ruby></ruby>")
    #expect(s().render() == "<s></s>")
    #expect(samp().render() == "<samp></samp>")
    #expect(script().render() == "<script></script>")
    #expect(section().render() == "<section></section>")
    #expect(select().render() == "<select></select>")
    #expect(small().render() == "<small></small>")
    #expect(span().render() == "<span></span>")
    #expect(strong().render() == "<strong></strong>")
    #expect(style().render() == "<style></style>")
    #expect(sub().render() == "<sub></sub>")
    #expect(summary().render() == "<summary></summary>")
    #expect(sup().render() == "<sup></sup>")
    #expect(table().render() == "<table></table>")
    #expect(tbody().render() == "<tbody></tbody>")
    #expect(td().render() == "<td></td>")
    #expect(template().render() == "<template></template>")
    #expect(textarea().render() == "<textarea></textarea>")
    #expect(tfoot().render() == "<tfoot></tfoot>")
    #expect(th().render() == "<th></th>")
    #expect(thead().render() == "<thead></thead>")
    #expect(time().render() == "<time></time>")
    #expect(title().render() == "<title></title>")
    #expect(tr().render() == "<tr></tr>")
    #expect(u().render() == "<u></u>")
    #expect(ul().render() == "<ul></ul>")
    #expect(`var`().render() == "<var></var>")
    #expect(video().render() == "<video></video>")

    // Self-closing elements
    #expect(area().render() == "<area />")
    #expect(base().render() == "<base />")
    #expect(br().render() == "<br />")
    #expect(col().render() == "<col />")
    #expect(embed().render() == "<embed />")
    #expect(hr().render() == "<hr />")
    #expect(img().render() == "<img />")
    #expect(input().render() == "<input />")
    #expect(link().render() == "<link />")
    #expect(meta().render() == "<meta />")
    #expect(source().render() == "<source />")
    #expect(track().render() == "<track />")
    #expect(wbr().render() == "<wbr />")
}

